[1m============================= test session starts ==============================[0m
platform linux -- Python 3.10.12, pytest-6.2.5, py-1.10.0, pluggy-0.13.0
cachedir: /home/vboxuser/ros2_ws/build/launch_testing_examples/.pytest_cache
rootdir: /home/vboxuser/ros2_ws/src/examples/launch_testing/launch_testing_examples
plugins: ament-lint-0.14.4, ament-copyright-0.14.4, launch-testing-ros-0.24.2, launch-pytest-2.0.4, launch-testing-2.0.4, ament-xmllint-0.14.4, ament-pep257-0.14.4, ament-mypy-0.14.4, ament-flake8-0.14.4, repeat-0.9.1, cov-3.0.0, rerunfailures-10.2, timeout-2.1.0, mock-3.6.1, colcon-core-0.19.0
[1mcollecting ... [0m[1m
collecting 1 item                                                              [0m[1m
collected 9 items                                                              [0m

launch_testing_examples/check_msgs_launch_test.py [32m.[0m[33m                      [ 11%][0m
launch_testing_examples/check_multiple_nodes_launch_test.py [32m.[0m[33m            [ 22%][0m
launch_testing_examples/check_node_launch_test.py [32m.[0m[33m                      [ 33%][0m
launch_testing_examples/hello_world_launch_test.py [32m.[0m[33m                     [ 44%][0m
launch_testing_examples/record_rosbag_launch_test.py [32m.[0m[33m                   [ 55%][0m
launch_testing_examples/set_param_launch_test.py [32m.[0m[33m                       [ 66%][0m
test/test_copyright.py [32m.[0m[33m                                                 [ 77%][0m
test/test_flake8.py [32m.[0m[33m                                                    [ 88%][0m
test/test_pep257.py [32m.[0m[33m                                                    [100%][0m

[33m=============================== warnings summary ===============================[0m
launch_testing_examples/check_msgs_launch_test.py::launch_testing_examples.check_msgs_launch_test
  Warning: Exception in thread Thread-1 (spin)
  
  Traceback (most recent call last):
    File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
      self.run()
    File "/usr/lib/python3.10/threading.py", line 953, in run
      self._target(*self._args, **self._kwargs)
    File "/opt/ros/iron/lib/python3.10/site-packages/rclpy/executors.py", line 295, in spin
      self.spin_once()
    File "/opt/ros/iron/lib/python3.10/site-packages/rclpy/executors.py", line 787, in spin_once
      self._spin_once_impl(timeout_sec)
    File "/opt/ros/iron/lib/python3.10/site-packages/rclpy/executors.py", line 776, in _spin_once_impl
      handler, entity, node = self.wait_for_ready_callbacks(timeout_sec=timeout_sec)
    File "/opt/ros/iron/lib/python3.10/site-packages/rclpy/executors.py", line 762, in wait_for_ready_callbacks
      return next(self._cb_iter)
    File "/opt/ros/iron/lib/python3.10/site-packages/rclpy/executors.py", line 670, in _wait_for_ready_callbacks
      raise ExternalShutdownException()
  rclpy.executors.ExternalShutdownException

test/test_flake8.py::test_flake8
test/test_flake8.py::test_flake8
  Warning: SelectableGroups dict interface is deprecated. Use select.

-- Docs: https://docs.pytest.org/en/stable/warnings.html
- generated xml file: /home/vboxuser/ros2_ws/build/launch_testing_examples/pytest.xml -
[33m======================== [32m9 passed[0m, [33m[1m3 warnings[0m[33m in 41.52s[0m[33m ========================[0m
